@host = http://192.168.11.6:11112

### 切換到 DisplayPort（DDC 15）
GET {{host}}/switch/15
Accept: application/json

### 切換到 USB-C / Type-C（DDC 16）
GET {{host}}/switch/16
Accept: application/json

### 切換到 HDMI 1（DDC 17）
GET {{host}}/switch/17
Accept: application/json

###
